### ISSUE TITLE
Try Julia!

### ISSUE THREAD

**Issue by davibarreira** [cpmech/russell#1]
Professor, como tão as coisas?! O senhor devia dar uma olhada em Julia (my new favorite language) :D, estão desenvolvendo um pacote voltado justamente pra educação de computação científica (https://github.com/fonsp/Pluto.jl) e acho que se encaixaria muito bem no seu curso da UQ (inclusive tem esse curso novo no MIT que usa Julia - https://computationalthinking.mit.edu/Spring21/).

Abraço!

**Comment by cpmech** [comment]
Opa. Que legal. Vou dar uma olhada sim. Obrigado!
