### ISSUE TITLE
Add Lambert W function to this library?

### ISSUE THREAD

**Issue by JSorngard** [cpmech/russell#130]
Hello!

I recently finished an implementation of the [Lambert W function](https://en.wikipedia.org/wiki/Lambert_W_function) in pure Rust: https://github.com/JSorngard/lambert_w. Would you be interested in integrating it in this crate?

**Comment by cpmech** [comment]
Hi, yes, this sounds like an interesting idea. A PR is mostly welcoming 😊

**Comment by cpmech** [comment]
Hi again. I see that LambertW is available in the *special* crate: https://github.com/stainless-steel/special/blob/main/src/lambert_w.rs, which wraps your library. So, to avoid further fragmentation of the Rust ecosystem, I'd rather add links to your library from here.

**Comment by cpmech** [comment]
Hi again; thank you for the suggestion. I've checked your `lambert_w` crate and found it very interesting. Your crate is very organized and tested! So, I think it's best to add a link from `russell_lab` to `lambert_w`. I just did that via PR https://github.com/cpmech/russell/pull/131. Potential researchers may find the link on the main Readme file and also in the library main file published here: https://docs.rs/russell_lab/latest/russell_lab/. Kind regards. Dorival

**Comment by cpmech** [comment]
By the way, although I base my Beta function implementation on Cephes, I spent a lot of time checking the original method and algorithm to make sure everything is all right. [See this comment](https://github.com/cpmech/russell/blob/844ea0a1e232f03552d825d983a25301c5855109/russell_lab/src/math/beta.rs#L148) and this [other comment](https://github.com/cpmech/russell/blob/844ea0a1e232f03552d825d983a25301c5855109/russell_lab/src/math/beta.rs#L255). All code in `russell` has been carefully implemented and tested. I have also compared the results with Mathematica. I would like to have the time to implement the Lambert W function myself. Fortunately, we have your fantastic code! Cheers.

**Comment by JSorngard** [comment]
I understand, then I thank you again for your consideration, and for linking to my crate, and close the issue :)
