### ISSUE TITLE
(Generalized) eigenvalues for complex matrices

### ISSUE THREAD

**Issue by MaxRang** [cpmech/russell#82]
Hi,

Thank you for creating this library! It will be very useful for me in my attempts at rewriting some old FORTRAN codes to Rust.

For my specific purpose, I need generalized eigenvalue solvers (i.e. dggev) and complex matrix eigenvalue solvers (zggev, zheev, zgeev). Are there currently plans to add these?

Thanks!

**Comment by cpmech** [comment]
Hi, yes! these four functions (and more) are coming soon.

**Comment by cpmech** [comment]
These functions are now available (`russell_lab` version v0.9.0):

* dggev -- wrapped by [mat_gen_eigen](https://docs.rs/russell_lab/0.9.0/russell_lab/matrix/fn.mat_gen_eigen.html)
* zggev -- wrapped by [complex_mat_gen_eigen](https://docs.rs/russell_lab/0.9.0/russell_lab/matrix/fn.complex_mat_gen_eigen.html)
* zheev -- wrapped by [complex_mat_eigen_herm](https://docs.rs/russell_lab/0.9.0/russell_lab/matrix/fn.complex_mat_eigen_herm.html)
* zgeev -- wrapped by [complex_mat_eigen](https://docs.rs/russell_lab/0.9.0/russell_lab/matrix/fn.complex_mat_eigen.html)

Feel free to suggest more functions!

**Comment by MaxRang** [comment]
Thank you for the amazingly fast implementation!
